export const PATIENT_DISCHARGE_REQUEST = "PATIENT_DISCHARGE_REQUEST"
export const PATIENT_DISCHARGE_SUCCESS = "PATIENT_DISCHARGE_SUCCESS"
export const PATIENT_DISCHARGE_FAILURE = "PATIENT_DISCHARGE_FAILURE"
