export const PATIENT_OF_HOSPITAL_REQUEST = "PATIENT_OF_HOSPITAL_REQUEST";
export const PATIENT_OF_HOSPITAL_SUCCESS = 'PATIENT_OF_HOSPITAL_SUCCESS';
export const PATIENT_OF_HOSPITAL_FAILURE = "PATIENT_OF_HOSPITAL_FAILURE";
