export const FETCH_SEVERITY_TYPES_REQUEST = "FETCH_SEVERITY_TYPES_REQUEST"
export const FETCH_SEVERITY_TYPES_SUCCESS = "FETCH_SEVERITY_TYPES_SUCCESS"
export const FETCH_SEVERITY_TYPES_FAILURE = "FETCH_SEVERITY_TYPES_FAILURE"
