export const LOGIN_USER_REQUEST = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const PATIENT_REGISTER_REQUEST = "PATIENT_REGISTER_REQUEST";
export const PATIENT_REGISTER_SUCCESS = 'PATIENT_REGISTER_SUCCESS';
export const PATIENT_REGISTER_ERROR = "PATIENT_REGISTER_ERRORS";

export const PERSON_REGISTER_REQUEST = "PERSON_REGISTER_REQUEST";
export const PERSON_REGISTER_SUCCESS = 'PERSON_REGISTER_SUCCESS';
export const PERSON_REGISTER_ERROR = "PERSON_REGISTER_ERROR";

