export const FETCH_ROLE_TYPES_REQUEST = "FETCH_ROLE_TYPES_REQUEST";
export const FETCH_ROLE_TYPES_SUCCESS = "FETCH_ROLE_TYPES_SUCCESS";
export const FETCH_ROLE_TYPES_FAILURE = "FETCH_ROLE_TYPES_FAILURE";