export const SELECT_LEVEL = "SELECTED_LEVEL";
export const SELECT_DATE = "SELECTED_DATE";
export const SELECT_HOSPITAL = "SELECTED_HOSPITAL";
export const SELECT_DISTRICT = "SELECTED_DISTRICT";

export const FETCH_COVID_STATS_REQUEST = "FETCH_COVID_STATS_REQUEST";
export const FETCH_COVID_STATS_SUCCESS = "FETCH_COVID_STATS_SUCCESS";
export const FETCH_COVID_STATS_FAILURE = "FETCH_COVID_STATS_FAILURE";
