export const FETCH_HOSPITAL_REQUEST = "FETCH_HOSPITAL_REQUEST";
export const FETCH_HOSPITAL_SUCCESS = "FETCH_HOSPITAL_SUCCESS";
export const FETCH_HOSPITAL_FAILURE = "FETCH_HOSPITAL_FAILURE";

export const FETCH_HOSPITAL_BY_ID_REQUEST = "FETCH_HOSPITAL_BY_ID_REQUEST";
export const FETCH_HOSPITAL_BY_ID_SUCCESS = "FETCH_HOSPITAL_BY_ID_SUCCESS";
export const FETCH_HOSPITAL_BY_ID_FAILURE = "FETCH_HOSPITAL_BY_ID_FAILURE";